node:
  root: tratao            # 根节点名
  nodeMutex: nodemutex    # 服务器互斥锁节点名
  nodePart: nodepart3      # 服务器分片节点名

zookeeper:
  addrs: 192.168.1.104:2181    # server address list
  timeout: 10                  # session timeout, in seconds
  watchtime: 10                # node watch time, in seconds

redis:
  addr: 192.168.1.104:6379    # server address
  maxConn: 5                  # max number connections in pool
  password: tratao            # password
  database:                   # default value is 0

rabbitmq:
  ip: 192.168.1.104           # server ip
  port: 5672                  # server port
  user: tratao                # user
  password: tratao            # password

check:
  serverName: "CKServer1"   # Check Alarm Server 名称，具有唯一性，其他服务器需要修改为不同名称
  pipeExecCount: 1000          # pipeline 每次最大查询数量
  maxSend: 10                  # 最大发送线程数
  maxReceive: 10               # 最大接收线程数
  alarmTickTime: 10            # 预警定时器时间（秒）
  exrateTickTime: 60           # 汇率定时器时间（秒）
  pushMsgTickTime: 5           # 推送消息定时器时间（秒）
  pushMsgQueue: "msg_queue"    # 推送队列名称

http:
  alarmPath: "/api/alarm"      # 预警接口根路径
  listenAddr: 8080             # API服务器端口

xiaomi:
  appSecret: "Yh5kSrxQOhhgXttyEgBpow=="              # 小米appSecret
  appPkgName: "com.example.traveltao.xcpushdemo"     # 小米app包名

meizu:
  appId: "115260"                                    # 魅族appId
  appSecret: "14854195ceb84bc4b7c619e3dd3e7f80"      # 魅族appSecret

huawei:
  appId: "100384977"                                 # 华为appId
  appSecret: "976b53ce5707fff89181f6412418102d"      # 华为appSecret
  appPkgName: "com.example.traveltao.xcpushdemo"     # 华为app包名

ios:
  cerPath: "/Users/traveltao/test/notification.p12"  # IOS证书
  cerPass: "123456"                                  # IOS证书密码

fcm:
  cfgPath: "/Users/traveltao/test/xcpushdemo-firebase-adminsdk-iy30t-340376f811.json" # google秘钥

test:
  alived: true
  percent: 34.55
